### ISSUE TITLE
Dimdoors dims save too often

### ISSUE THREAD

**Issue by ZexMaxwell001** [StevenRS11/DimDoors#102]
I keep seeing my server console saving about every other min even though no one is currently using the doors or on the server.

Forge 952 1.6
no server impact at this moment.

**Comment by SenseiKiwi** [comment]
This is straightforward to fix. The reason that the messages appears every so often is because we save the rift-related data for each dimension every time the world saves. This happens every 30 seconds, I think. We output a message saying that saving is taking place, but assuming our dirty flags are working right, no actual saving is taking place. We should only save data for dimensions that have had their data change recently. The solution to the log spam would be not to output messages unless we actually do save something, or perhaps we shouldn't do it at all.

**Comment by StevenRS11** [comment]
SenseiKiwi Fixed
